### ISSUE TITLE
Crash unable to launch 

### ISSUE THREAD

**Issue by kryteyk** [SuperMartijn642/RechiseledCreate#1]
I have a problem starting a modded 1.18.2 minecraft forge with create, re-chiseled and re-chiseled:create addition. i tried a new forge version, several create versions and flywheel versions. this is the crash report i got 
[crash-2023-07-20_20.45.41-fml.txt](https://github.com/SuperMartijn642/RechiseledCreate/files/12113150/crash-2023-07-20_20.45.41-fml.txt)

**Comment by SuperMartijn642** [comment]
Please fill in the proper template with the requested information.
You are using an older version of Create, please update Create.

**Comment by kryteyk** [comment]
Which version do you recommend? I tried it with the latest version

**Comment by SuperMartijn642** [comment]
The version of Create you are using in the log you shared is over half a year old 🤔

**Comment by kryteyk** [comment]
[crash-2023-07-21_16.26.52-fml.txt](https://github.com/SuperMartijn642/RechiseledCreate/files/12129654/crash-2023-07-21_16.26.52-fml.txt)
Retried it with a new version of Create (0.5.1b) and the same issue with 0.5.1c

**Comment by SuperMartijn642** [comment]
Rechiseled: Create requires Rechiseled 1.1.1 or newer, you have 1.0.13 installed. Not sure why Forge isn't  showing the warning screen for the dependency, might be some other mod you have installed that breaks that.

**Comment by Kleptoplasm** [comment]
Same here i think 
[latest.log](https://github.com/SuperMartijn642/RechiseledCreate/files/12927740/latest.log)

**Comment by Kleptoplasm** [comment]
im  going to open a new issue chat thing with a crash log with only the required mods
