### ISSUE TITLE
[Crash] Cannot register custom item renderer for item 'minecraft:air' without EditableClientItemExtensions render properties!

### ISSUE THREAD

**Issue by GenesisPT** [SuperMartijn642/RechiseledCreate#11]
**Version Info**
- Minecraft, 1.20.1
- Rechiseled, 1.1.5c
- Create, 1.20.1-0.5.1.f
- Rechiseled: Create, 1.0.2

**Steps to Reproduce**
Try to open the game

**Crash report (~/logs/latest.log)**
https://pastebin.com/wWSmG0Rg

**Comment by SuperMartijn642** [comment]
Based on a discussion on Discord, this was determined to be caused by XK's Decoration.
