### ISSUE TITLE
[Bug] ... Translation bug 

### ISSUE THREAD

**Issue by zachsai** [SuperMartijn642/RechiseledCreate#2]
**Version Info**
- Minecraft, 1.20.1
- Rechiseled, 1.1.1
- Create, 0.5.1.d
- Rechiseled: Create, 1.0.0

Seems to be translation bug:
![image](https://github.com/SuperMartijn642/RechiseledCreate/assets/63996164/c53712b3-edf7-48d3-b39a-02548dafc57a)

**Comment by SuperMartijn642** [comment]
Seems to be working fine with just Rechiseled: Create and its dependencies on Forge for 1.20.1:
![image](https://github.com/SuperMartijn642/RechiseledCreate/assets/12382965/eea357dd-12b3-4572-8187-5bf75d15a328)
