### ISSUE TITLE
[Feature] ... Update to 1.20.X (Fabric)

### ISSUE THREAD

**Issue by Sepera-okeq** [SuperMartijn642/RechiseledCreate#4]
**Is your feature request related to a problem? Please describe.**
This mod is not available for fabric 1.20

**Describe the solution you'd like**
Support 1.20.X ver (fabric loader)

**Comment by SuperMartijn642** [comment]
> Support 1.20.X ver (fabric loader)

I can't as there is no Create for Fabric on 1.20.X

**Comment by velikoss** [comment]
now there is
