### ISSUE TITLE
Invalid paths to textures

### ISSUE THREAD

**Issue by Xyphenore** [SuperMartijn642/RechiseledCreate#5]
**Version Info**
- Minecraft: 1.20.1
- Rechiseled: 1.1.4
- Create: 0.5.1d
- Rechiseled: Create: 1.0.0a
- Fusion: 1.0.5a
- Forge: 47.1.47
- SuperMartijn642 CoreLib: 1.1.12a
- SuperMartijn642 ConfigLib: 1.1.8

**Description of the Bug**

The console prints two errors about invalid paths to texture.

Errors:

- Invalid path in pack: rechiseledcreate:textures/block/template_overlay simple.png, ignoring
- Invalid path in pack: rechiseledcreate:textures/block/template simple.png, ignoring

**Steps to Reproduce**

- Install the mod.
- Run the game with the output console.
- Create a world.
- Errors are printed to console.

**Comment by SuperMartijn642** [comment]
Apart from the warning messages, it shouldn't really affect anything so I'll just change it whenever I update the mod again.

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.0.1. Thank you for reporting the issue!
