### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by Kleptoplasm** [SuperMartijn642/RechiseledCreate#6]
**Version Info**
- Minecraft, 1.18.2
- Rechiseled, 1.1.4a
- Create, v0.5.1.c(Beta)
- Rechiseled: Create, 1.0.1

**Steps to Reproduce**
Launch the game with the mod and all dependencies

**Crash report (~/logs/latest.log)**
See attached file
[2latest.log](https://github.com/SuperMartijn642/RechiseledCreate/files/12941460/2latest.log)

**Comment by Kleptoplasm** [comment]
im on linux using a steamdeck and ATlauncher

**Comment by SuperMartijn642** [comment]
Seems something in newer version of my core library broke it.
It should be fixed now in version 1.0.1a for Fabric 1.18. Thank you for reporting the issue!
