### ISSUE TITLE
Not Updated to Create 0.5.1-f-build.1335

### ISSUE THREAD

**Issue by Voidmaster01** [SuperMartijn642/RechiseledCreate#9]
**Version Info**
- Minecraft 1.20.1
- Rechiseled: Create 1.0.2

**Description of the Bug**
Rechisled: Create, is not updated to support the latest create Update which has broken many mods recently

**Steps to Reproduce**
install with latest create,
 run

**Comment by SuperMartijn642** [comment]
Is this for the Fabric or the Forge version of Create?

**Comment by Voidmaster01** [comment]
This is for fabric

**Comment by rilakuma123** [comment]
Works for me in my brief testing. Does it crash? If so, do you have a log and crash report?

**Comment by SuperMartijn642** [comment]
I can confirm that indeed the game runs fine with Rechiseled: Create and the latest version of Create Fabric for 1.20.1.
